
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";



export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";


export const TOKEN_USER_REQ = "TOKEN_USER_REQ"
export const TOKEN_USER_SUCCESS = "TOKEN_USER_SUCCESS"
export const TOKEN_USER_FAILED = "TOKEN_USER_FAILED"

export const USER_LOGOUT = "USER_LOGOUT"
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE"
export const USER_SAVE_INFO_UPDATE = "USER_SAVE_INFO_UPDATE"
export const USER_PROFILE_PHOTO_UPDATE = "USER_PROFILE_PHOTO_UPDATE"
export const USER_PROFILE_COVER_PHOTO_UPDATE = "USER_PROFILE_COVER_PHOTO_UPDATE"
export const FEATURED_SLIDER_UPDATE = "FEATURED_SLIDER_UPDATE"


export const GET_ALL_USERS_REQ = "GET_ALL_USERS_REQ"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS = "GET_ALL_USERS"

